### ISSUE TITLE
Error if feature style is icon when it's selected with animate: true

### ISSUE THREAD

**Issue by cs09g** [Viglino/OL3-AnimatedCluster#14]
When you set featureStyle on ol.interaction.SelectCluster as ol.style.Style(image: ol.style.Icon), an error occurs. Error string is explained [here](https://github.com/openlayers/openlayers/issues/6733).

One thing weird is when there are clustered feature and unclustered feature(it is a feature in cluster layer but with no children), it works fine. but when there's only clustered features(all features has its children), the error happens. 
and animate:false doesn't make an error. 

the example's [here](https://jsfiddle.net/ogvxLrxt/1/)

**Comment by cs09g** [comment]
Checked when I try to set style for Icon feature before adding the feature to map. reported [here](https://github.com/openlayers/openlayers/issues/6733)

**Comment by Viglino** [comment]
Hello,

The problem is you don't define any image when you have only 1 feature in the cluster.
In the getStyle() function, you have to return an image when size == 1 otherwise it tries to draw an undefined image (and drawing will stop).
You also have to preload the image or it will not been loaded before rendrered (when all features are in a cluster) > use img instead of src or use the load function (https://openlayers.org/en/latest/apidoc/ol.style.Icon.html#load).

See the example here: https://jsfiddle.net/Viglino/a2vLcbu1/4/

@+

**Comment by cs09g** [comment]
@Viglino style.getImage().load() works! Thank you.
